### ISSUE TITLE
Bug?: Token Hotbar does not clear when no token is selected  

### ISSUE THREAD

**Issue by Norc** [janssen-io/foundry-token-hotbar#1]
_Test Info_:
Foundry 0.62, D&D 0.92, Token Hotbar 1.2.3, Electron app as GM, only module installed in test world. All tokens are unlinked SRD monsters. Same behavior happened with linked tokens.

_Test Steps_:
1. Click a token that has a token hotbar defined with at least one macro on it
2. Deselect the token by selecting no tokens

**Current behavior**: Macro remains on token hotbar
**Expected behavior**: Token hotbar is cleared (or maybe reverts to a set of macros, like hotbars 1-4) until another token with a defined hotbar is selected.

**Comment by Norc** [comment]
I'm thinking maybe it should revert to the last hotbar active before the token hotbar was active instead?

**Comment by janssen-io** [comment]
I think both solutions are great. (y)

1. Show the regular 'user' hotbar with macros that were put there when no tokens were selected.
2. Switch to the last active hotbar. This would make more sense with relation to #3 and also has the benefit that I can warn when no tokens are selected when the user puts a macro on the token hotbar. I think I'll go with this option.

**Comment by janssen-io** [comment]
Marked as duplicate, as the solution is also proposed in #3 (Auto-Hotbar toggling).
