### ISSUE TITLE
Update Failed

### ISSUE THREAD

**Issue by Rinzlers** [janssen-io/foundry-token-hotbar#11]
When trying to update the module I get the attached error.
![image](https://user-images.githubusercontent.com/31813724/84712074-96131700-af1c-11ea-89bb-5f1e79f23852.png)

**Comment by janssen-io** [comment]
Just around that time I was updating my manifest and download links. Can you try again?

And if it still doesn’t work, can you tell me what OS and version of Foundry and Token Hotbar you are using?

**Comment by Rinzlers** [comment]
I got it to work. Thanks for your help.  Bad timing on my part.
