### ISSUE TITLE
Feature Request: Option to set same macro for all unlinked tokens of that protype

### ISSUE THREAD

**Issue by Norc** [janssen-io/foundry-token-hotbar#2]
Almost always (always?), I'd like to set token hotbars for ALL unlinked tokens of the same time. For instance, I'd like to give every Skeleton a shortbow attack macro, not just the one skeleton I happened to click.

Maybe have this as a setting so that the current behavior can be preserved, if someone wants it for some reason? I'm not sure what the use case is for that though.

**Comment by janssen-io** [comment]
Great suggestion, Norc! However, this should already be possible since v1.2.3
In the module settings you can check 'Always link to actor'.

![image](https://user-images.githubusercontent.com/33344942/84350745-30402b80-abba-11ea-9208-64bb9f81a652.png)

Let me know if this works for you. :)

**Comment by Norc** [comment]
Ha, it does, thanks. Didn't notice the new arrival.
