### ISSUE TITLE
Custom-hotbar listed as dependency which is not allowing settings to be saved in module managment

### ISSUE THREAD

**Issue by Pyroman2xxx** [janssen-io/foundry-token-hotbar#27]
The title says it all. I was under the impression that custom-hotbar was supported but not required. I do not wish to use custom-hotbar with token-hotbar but this is preventing me from enabling token-hotbar.

Perhaps I am doing something wrong?

Thank you!

**Comment by janssen-io** [comment]
That is indeed not good. :( I was hoping the new format would support optional dependencies, but I'll remove it for the time being.
Thank you for the heads-up!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by janssen-io** [comment]
Solved in v4.0.6 👍 

Many thanks for logging the issue!
