### ISSUE TITLE
Feature Request: Option for a non-token hotbar

### ISSUE THREAD

**Issue by shinkei13** [janssen-io/foundry-token-hotbar#29]
Current functionality maintains the most recent token's hotbar whenever deselecting that token. 

I was wondering if it was possible to have a hotbar saved in the interim, whenever no token is selected. This way, I can have separate hotbars for each token, and a main hotbar when there are no tokens in focus (such as for storytelling, or script macros).

**Comment by janssen-io** [comment]
My apologies for the late reply, @shinkei13

This is a great idea, it's been on the virtual roadmap for quite some time. I'll have a look at it again. 👍

**Comment by janssen-io** [comment]
Not as bad as I expected! 

If you'd like you can test out a preview over here: https://fvtt.janssen.io/tokenhotbar/alpha/module.json

**Comment by janssen-io** [comment]
I expect this to be released to stable by the end of October. :)
