### ISSUE TITLE
Got an error for "tokens" property set to null

### ISSUE THREAD

**Issue by yoshikidneo** [janssen-io/foundry-token-hotbar#32]
This happens on load, doesn't seem to impact the use of the module but want to make sure you're aware.

foundry.js:2499 TypeError: Cannot read property 'tokens' of null
    at TokenHotbar.js:1
    at Function._call (foundry.js:2496)
    at Function.call (foundry.js:2481)
    at CustomHotbar._render (foundry.js:4547)

**Comment by janssen-io** [comment]
Which version of Foundry is this with? Any other modules installed? Does this error still occur when you disable the other modules?

**Comment by yoshikidneo** [comment]
> Hey Yoshi, thanks for reporting this!
> 
> I can't seem to reproduce this myself. Could you answer the following questions?
> 
> * Which version of Foundry is this with?
> * Any other modules installed?
> * Does this error still occur when you disable the other modules?

I'm using Foundry v0.7.7
I do have a good amount of modules setup, and after making a new world to do some testing, I have found that only having the hotbars enabled there isn't an issue. 

My guess is that there is something else happening with another module, and for whatever reason it pointed to this one as the error as well as custom hotbar.
