### ISSUE TITLE
Created macros won't save and disappear next time the token is selected

### ISSUE THREAD

**Issue by InnilToo** [janssen-io/foundry-token-hotbar#33]
When I try to assign macros to a specific token the next time I select such token the macros are missing. They can still be found in the Macros Directory. There are no error messages in the console.
I managed to use a temporary workaround with Custom Hotbar module that seems to be retaining assigned macros. If the Custom Hotbar is then disabled the macros will appear on the desired hotbar (in my case number 5).

**Comment by janssen-io** [comment]
Thanks for the heads-up, Innil! I haven't had the time to test the module with Foundry 0.7.7 yet, but I'll give it a look soon. :)

**Comment by janssen-io** [comment]
I think I have located the issue (the preUpdateUser hook does not seem to fire anymore), so I'll be looking into using the (new since 0.7.x) hotbarDrop hook. Hopefully, I can push out a fix this weekend.

**Comment by janssen-io** [comment]
Version 4.2.0 should be compatible again.
