### ISSUE TITLE
Manifest no longer valid?

### ISSUE THREAD

**Issue by jalensailin** [janssen-io/foundry-token-hotbar#36]
I hit the Update All button and got a warning flag (I already had Token Hotbar installed). I tried uninstalling and reinstalling to see if that would fix the issue but unfortunately it now won't redownload and throws a similar error (see below). I tried downloading from github and installing manually, but when I do that there is no way to access the settings for some reason (probably didnt install correctly). Not sure what changed but thought I'd bring it to your attention. Thanks!

![image](https://user-images.githubusercontent.com/72114365/101961981-f7205c80-3bd8-11eb-8658-6a90e63b39f8.png)

**Comment by janssen-io** [comment]
Thanks for the mention. It seems like I let my SSL certificates expire. It should work now. Sorry for the inconvenience!
